language: ruby
cache: bundler
rvm:
  - 2.6
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: bundle exec jekyll build
deploy:
  provider: pages
  local_dir: ./_site
  skip_cleanup: true
  keep_history: true
  github_token: GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false